"""empty message

Revision ID: 2315830ced38
Revises: d094c6365cf9
Create Date: 2025-05-18 10:28:35.281059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2315830ced38'
down_revision: Union[str, None] = 'd094c6365cf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('name', sa.String(length=40), nullable=False))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('word', sa.Column('description', sa.String(length=150), nullable=False))
    op.alter_column('word', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=45),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('word', 'name',
               existing_type=sa.String(length=45),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('word', 'description')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('decks', 'name')
    # ### end Alembic commands ###
