"""empty message

Revision ID: 975e0283fe76
Revises: 2315830ced38
Create Date: 2025-05-20 18:51:24.683183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '975e0283fe76'
down_revision: Union[str, None] = '2315830ced38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('translate', sa.String(length=64), nullable=False))
    op.alter_column('word', 'description',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=350),
               existing_nullable=False)
    op.create_index(op.f('ix_word_count'), 'word', ['count'], unique=False)
    op.create_index(op.f('ix_word_name'), 'word', ['name'], unique=False)
    op.create_index(op.f('ix_word_rank'), 'word', ['rank'], unique=False)
    op.create_index(op.f('ix_word_translate'), 'word', ['translate'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_translate'), table_name='word')
    op.drop_index(op.f('ix_word_rank'), table_name='word')
    op.drop_index(op.f('ix_word_name'), table_name='word')
    op.drop_index(op.f('ix_word_count'), table_name='word')
    op.alter_column('word', 'description',
               existing_type=sa.String(length=350),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_column('word', 'translate')
    # ### end Alembic commands ###
