"""empty message

Revision ID: a02f6f949b51
Revises: 2eae53577355
Create Date: 2025-05-17 09:38:14.396106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a02f6f949b51'
down_revision: Union[str, None] = '2eae53577355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('name', sa.String(length=40), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'name')
    # ### end Alembic commands ###
